<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Contratos: interfaces de servicios y repositorios, DTOs, excepciones.
    REGLA: referencia unicamente CrossCutting.
  -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Transacciones.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Transacciones.CrossCutting\Transacciones.CrossCutting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>