<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Logica de negocio: implementa las interfaces de Core.Services.
    REGLA: NO referencia Transacciones.Data. Consume ISolicitudRepository por DI.
  -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Transacciones.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Transacciones.Core\Transacciones.Core.csproj" />
    <ProjectReference Include="..\Transacciones.CrossCutting\Transacciones.CrossCutting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>